# Generated by Django 4.2.13 on 2024-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("posts", "0004_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="posts", to="tags.tag"),
        ),
    ]
