# Generated by Django 4.2.13 on 2024-06-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("opis", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "published"),
                            ("banned", "banned"),
                            ("pending", "pending"),
                        ],
                        default="pending",
                        max_length=9,
                    ),
                ),
                ("tags", models.ManyToManyField(related_name="photos", to="tags.tag")),
            ],
        ),
    ]
