# Generated by Django 4.2.13 on 2024-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="img",
            field=models.ImageField(null=True, upload_to="photos"),
        ),
    ]
