# Generated by Django 4.2.13 on 2024-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("photos", "0002_photo_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="img",
            field=models.ImageField(null=True, upload_to="photos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="photos", to="tags.tag"
            ),
        ),
    ]
