# Generated by Django 4.2.13 on 2024-06-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_alter_photo_img_alter_photo_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True, related_name="galleries", to="photos.photo"
                    ),
                ),
            ],
        ),
    ]
